sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - 1.41.0
branches:
  only:
  - master
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_script:
  - (cargo install mdbook --vers 0.3.5 --force || true)
script:
  - bash ci/build.sh
